"""The landing page publishes numbers with no API call behind them — prove they are real.

`/` renders entirely from `frontend/src/generated/landingData.ts`, which is generated by
`frontend/scripts/build-landing-data.mjs` from the committed artifacts and then committed
itself. That buys instant first paint, but it reintroduces the exact hazard this repo has
shipped twice: a figure that lives in the frontend and drifts away from the artifact it
claims to describe (`frontend/src/lib/volumeDecayCurveData.ts` is the surviving example of
the hand-transcribed pattern).

The generator alone is not a guard. A generated file can be hand-edited, or left stale
while the artifact under it is regenerated, and nothing would notice — the build would
still be green because the build only reads the committed file.

So these tests re-derive every published value straight from the artifacts and the tracked
DB and compare. They fail if:
  - anyone edits a number in the generated file by hand,
  - an artifact is regenerated and the generated file is not,
  - an artifact is regenerated from a dirty tree and reaches the page anyway,
  - the retracted 47.25% "naive baseline" figure is published as the optimizer's edge.

To see them fail on purpose: change any `"value"` in landingData.ts and run this file.
"""
from __future__ import annotations

import json
import re
import sqlite3
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
GENERATED = REPO / "frontend" / "src" / "generated" / "landingData.ts"
DB = REPO / "backend" / "supply_chain.db"

# Display values are rounded in the component, never in the data, so the generated
# numbers should match the artifact to full float precision.
TOL = 1e-9


def _load_generated() -> dict:
    """Pull the JSON literals back out of the generated TypeScript module."""
    if not GENERATED.exists():
        pytest.fail(
            f"{GENERATED.relative_to(REPO)} is missing — run "
            "`cd frontend && node scripts/build-landing-data.mjs` and commit the result."
        )
    src = GENERATED.read_text()

    def array(name: str) -> list:
        m = re.search(rf"export const {name}: \w+\[\] = (\[[\s\S]*?\n\])\n", src)
        assert m, f"could not find {name} in the generated module"
        return json.loads(m.group(1))

    counts = {}
    for key in ("parts", "distributors", "offers", "partsPriced", "distributorsQuoting"):
        m = re.search(rf"\n  {key}: (\d+),", src)
        assert m, f"generated module has no catalogue.{key} — regenerate it"
        counts[key] = int(m.group(1))
    caveat = json.loads(re.search(r"export const naiveBaselineCaveat = (\".*\")\n", src).group(1))
    return {
        "stats": {s["id"]: s for s in array("landingStats")},
        "proof": array("landingProofPoints"),
        "catalogue": counts,
        "caveat": caveat,
    }


def _artifact(name: str) -> dict:
    return json.loads((REPO / "docs" / name).read_text())


@pytest.fixture(scope="module")
def generated() -> dict:
    return _load_generated()


def test_cost_edge_matches_benchmark_artifact(generated):
    """The headline is the matched-pool comparison, not the naive-baseline one."""
    expected = abs(_artifact("benchmark_results.json")["headline"]["primary_save_pct"])
    assert generated["stats"]["cost-edge"]["value"] == pytest.approx(expected, abs=TOL)


def test_cvar_leverage_matches_frontier_artifact(generated):
    knee = _artifact("cvar_frontier.json")["primary"]["x10000"]["knee"]
    expected = knee["vs_risk_neutral"]["usd_of_cvar_removed_per_usd_of_expected_cost"]
    assert generated["stats"]["cvar-leverage"]["value"] == pytest.approx(expected, abs=TOL)


def test_forecast_mape_matches_backtest_artifact(generated):
    expected = _artifact("forecast_backtest.json")["prophet"]["overall"]["mape"] * 100
    assert generated["stats"]["forecast-mape"]["value"] == pytest.approx(expected, abs=TOL)


def test_wape_reduction_is_the_stated_formula(generated):
    """A derived figure must be reproducible from the two inputs it names."""
    chronos = _artifact("chronos_benchmark.json")
    naive = chronos["seasonal_naive"]["overall"]["wape"]
    model = chronos["chronos"]["overall"]["wape"]
    expected = (naive - model) / naive * 100
    stat = generated["stats"]["wape-reduction"]
    assert stat["value"] == pytest.approx(expected, abs=TOL)
    assert stat.get("derived") is True, "a derived number must be labelled derived on the page"


def test_shortfall_matches_diversification_frontier(generated):
    frontier = _artifact("diversification_frontier.json")["frontier"]
    k4 = next(row for row in frontier if row["k"] == 4)
    expected = k4["delta_targeted_expected_shortfall_vs_k1"]["mean"] * 100
    assert generated["stats"]["shortfall"]["value"] == pytest.approx(expected, abs=TOL)


def test_inference_latency_matches_chronos_artifact(generated):
    expected = _artifact("chronos_benchmark.json")["chronos"]["steady_state"]["median_ms"]
    assert generated["stats"]["latency"]["value"] == pytest.approx(expected, abs=TOL)


def _db_counts() -> dict:
    con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    try:
        one = lambda q: con.execute(q).fetchone()[0]  # noqa: E731
        return {
            "parts": one("SELECT COUNT(*) FROM components"),
            "distributors": one("SELECT COUNT(*) FROM distributors"),
            "offers": one("SELECT COUNT(*) FROM distributor_offers"),
            "partsPriced": one("SELECT COUNT(DISTINCT component_id) FROM distributor_offers"),
            "distributorsQuoting": one("SELECT COUNT(DISTINCT distributor_id) FROM distributor_offers"),
        }
    finally:
        con.close()


def test_catalogue_counts_match_the_served_database(generated):
    """The DB is tracked and is what production serves — the page must not outrun it."""
    assert generated["catalogue"] == _db_counts()


def test_the_page_does_not_pass_off_catalogue_size_as_priced_coverage(generated):
    """791 parts exist; 768 are priced. 92 distributors exist; 83 quote. Do not merge those.

    The page briefly read "791 real parts - 92 distributors - 8,176 live offers", which reads
    as though every catalogued part is priced by every distributor. 23 parts carry no offer at
    all and 9 distributors quote nothing.
    """
    db = _db_counts()
    cat = generated["catalogue"]
    assert cat["partsPriced"] <= cat["parts"]
    assert cat["distributorsQuoting"] <= cat["distributors"]

    row = next(p for p in generated["proof"] if "catalogue" in p["label"].lower())
    if db["partsPriced"] != db["parts"]:
        assert str(db["partsPriced"]) in row["detail"] and str(db["parts"]) in row["detail"], (
            "when coverage is partial the page must state BOTH the priced count and the total"
        )
    if db["distributorsQuoting"] != db["distributors"]:
        assert str(db["distributorsQuoting"]) in row["detail"], (
            "the page must state how many distributors actually quote, not just how many exist"
        )


def test_the_offers_are_never_described_as_live(generated):
    """`distributor_offers` has no date column, so freshness is unfalsifiable from the data.

    The vintage is a static 2024 snapshot asserted in backend/seeds/seed_db.py and
    docs/DATA_PROVENANCE.md. Calling it "live" claims something the schema cannot support —
    and the standing bar is that nothing published may be contradicted by the code.
    """
    con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    try:
        cols = {r[1].lower() for r in con.execute("PRAGMA table_info(distributor_offers)")}
    finally:
        con.close()
    dated = cols & {"updated_at", "observed_at", "fetched_at", "as_of", "created_at", "date"}
    assert not dated, (
        f"distributor_offers now has {dated} — if offers really are dated, revisit this test "
        "and the wording it guards rather than deleting it"
    )

    blob = " ".join(
        [p["detail"] + " " + p["label"] + " " + p["value"] for p in generated["proof"]]
        + [s["detail"] + " " + s["label"] for s in generated["stats"].values()]
    ).lower()
    assert "live offer" not in blob, "offers described as live, but nothing in the data dates them"

    row = next(p for p in generated["proof"] if "catalogue" in p["label"].lower())
    assert "snapshot" in row["detail"].lower(), "the static vintage must be stated, not implied"


def test_solve_quality_proof_point_matches_artifact(generated):
    """"Converged" and "proved optimal" are different counts — publish both, conflate neither.

    The artifact's own rule: converged := status == OPTIMAL (gap closed to zero) OR
    mip_gap_pct <= 5. Of 387 solves, 337 are OPTIMAL and 347 converged. The page briefly
    published 347 under the label "proved optimal", overstating the stronger claim by ten
    solves. This test exists so that cannot recur.
    """
    sq = _artifact("cvar_frontier.json")["solve_quality"]
    row = next(p for p in generated["proof"] if "CP-SAT" in p["label"])

    assert row["value"] == f"{sq['n_converged']} of {sq['n_solves']}"

    n_optimal = sq["counts_by_status"]["OPTIMAL"]
    if n_optimal != sq["n_converged"]:
        assert "proved optimal" not in row["label"], (
            f"label claims {sq['n_converged']} were proved optimal, but only {n_optimal} were"
        )
        assert str(n_optimal) in row["detail"], (
            "when converged > proved-optimal, the page must state the proved-optimal count too"
        )
        assert str(sq["convergence_gap_threshold_pct"]).rstrip("0").rstrip(".") in row["detail"], (
            "the gap tolerance that admitted the extra solves must be stated"
        )

    assert str(sq["n_not_converged"]) in row["detail"], (
        "the excluded non-converged solves must stay visible, not be quietly dropped"
    )


def test_reproduction_proof_point_matches_artifact(generated):
    check = _artifact("diversification_frontier.json")["run5_reproduction_check"]
    row = next(p for p in generated["proof"] if "reproduced" in p["label"])
    assert row["value"] == f"{check['matched']} of {check['checked']}"


def test_published_artifacts_were_generated_from_a_clean_tree(generated):
    """A dirty-tree artifact cannot be traced to a commit, so it must not reach the page."""
    for name in ("cvar_frontier.json", "diversification_frontier.json"):
        dirty = _artifact(name).get("provenance", {}).get("git", {}).get("dirty")
        assert dirty is False, f"docs/{name} stamps provenance.git.dirty={dirty}"


def test_the_retracted_naive_baseline_figure_is_not_published_as_the_edge(generated):
    """47.25% was once published as the optimizer's edge. It is not. It stays caveated."""
    for stat in generated["stats"].values():
        assert abs(stat["value"] - 47.25) > 0.01, (
            f"stat {stat['id']} publishes the retracted naive-baseline figure"
        )
    assert "naive" in generated["caveat"].lower()


def test_every_published_number_names_its_source(generated):
    """The differentiator of this project is traceability — enforce it structurally."""
    for stat in generated["stats"].values():
        assert stat["source"].strip(), f"{stat['id']} has no source"
        assert "→" in stat["source"] or stat["source"].startswith("backend/"), (
            f"{stat['id']} source is not a path into an artifact: {stat['source']!r}"
        )
    for row in generated["proof"]:
        assert row["source"].strip(), f"proof point {row['label']!r} has no source"
