"""The landing page publishes numbers with no API call behind them — prove they are real.

`/` renders entirely from `frontend/src/generated/landingData.ts`, which is generated by
`frontend/scripts/build-landing-data.mjs` from the committed artifacts and then committed
itself. That buys instant first paint, but it reintroduces the exact hazard this repo has
shipped twice: a figure that lives in the frontend and drifts away from the artifact it
claims to describe.

The generator alone is not a guard. A generated file can be hand-edited, or left stale
while the artifact under it is regenerated, and nothing would notice — the build would
still be green because the build only reads the committed file.

So these tests re-derive every published value straight from the artifacts and the tracked
DB and compare. They fail if:
  - anyone edits a number in the generated file by hand,
  - an artifact is regenerated and the generated file is not.

The sourcing-optimizer figures this page used to carry (cost edge, CVaR leverage,
diversification shortfall, CP-SAT solve quality) were removed with that optimizer; see
git tag `archive/sourcing-v1`.

To see them fail on purpose: change any `"value"` in landingData.ts and run this file.
"""
from __future__ import annotations

import json
import re
import shutil
import sqlite3
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
GENERATED = REPO / "frontend" / "src" / "generated" / "landingData.ts"
DB = REPO / "backend" / "supply_chain.db"

# Display values are rounded in the component, never in the data, so the generated
# numbers should match the artifact to full float precision.
TOL = 1e-9


def _load_generated() -> dict:
    """Pull the JSON literals back out of the generated TypeScript module."""
    if not GENERATED.exists():
        pytest.fail(
            f"{GENERATED.relative_to(REPO)} is missing — run "
            "`cd frontend && node scripts/build-landing-data.mjs` and commit the result."
        )
    src = GENERATED.read_text()

    def array(name: str) -> list:
        m = re.search(rf"export const {name}: \w+\[\] = (\[[\s\S]*?\n\])\n", src)
        assert m, f"could not find {name} in the generated module"
        return json.loads(m.group(1))

    counts = {}
    for key in ("parts", "distributors", "offers", "partsPriced", "distributorsQuoting"):
        m = re.search(rf"\n  {key}: (\d+),", src)
        assert m, f"generated module has no catalogue.{key} — regenerate it"
        counts[key] = int(m.group(1))
    return {
        "stats": {s["id"]: s for s in array("landingStats")},
        "proof": array("landingProofPoints"),
        "catalogue": counts,
    }


def _artifact(name: str) -> dict:
    return json.loads((REPO / "docs" / name).read_text())


@pytest.fixture(scope="module")
def generated() -> dict:
    return _load_generated()


def test_forecast_mape_matches_backtest_artifact(generated):
    expected = _artifact("forecast_backtest.json")["prophet"]["overall"]["mape"] * 100
    assert generated["stats"]["forecast-mape"]["value"] == pytest.approx(expected, abs=TOL)


def test_wape_reduction_is_the_stated_formula(generated):
    """A derived figure must be reproducible from the two inputs it names."""
    chronos = _artifact("chronos_benchmark.json")
    naive = chronos["seasonal_naive"]["overall"]["wape"]
    model = chronos["chronos"]["overall"]["wape"]
    expected = (naive - model) / naive * 100
    stat = generated["stats"]["wape-reduction"]
    assert stat["value"] == pytest.approx(expected, abs=TOL)
    assert stat.get("derived") is True, "a derived number must be labelled derived on the page"


def test_inference_latency_matches_chronos_artifact(generated):
    expected = _artifact("chronos_benchmark.json")["chronos"]["steady_state"]["median_ms"]
    assert generated["stats"]["latency"]["value"] == pytest.approx(expected, abs=TOL)


def _db_counts() -> dict:
    con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    try:
        one = lambda q: con.execute(q).fetchone()[0]  # noqa: E731
        return {
            "parts": one("SELECT COUNT(*) FROM components"),
            "distributors": one("SELECT COUNT(*) FROM distributors"),
            "offers": one("SELECT COUNT(*) FROM distributor_offers"),
            "partsPriced": one("SELECT COUNT(DISTINCT component_id) FROM distributor_offers"),
            "distributorsQuoting": one("SELECT COUNT(DISTINCT distributor_id) FROM distributor_offers"),
        }
    finally:
        con.close()


def test_catalogue_counts_match_the_served_database(generated):
    """The DB is tracked and is what production serves — the page must not outrun it."""
    assert generated["catalogue"] == _db_counts()


def test_the_page_does_not_pass_off_catalogue_size_as_priced_coverage(generated):
    """791 parts exist; 768 are priced. 92 distributors exist; 83 quote. Do not merge those.

    The page briefly read "791 real parts - 92 distributors - 8,176 live offers", which reads
    as though every catalogued part is priced by every distributor. 23 parts carry no offer at
    all and 9 distributors quote nothing.
    """
    db = _db_counts()
    cat = generated["catalogue"]
    assert cat["partsPriced"] <= cat["parts"]
    assert cat["distributorsQuoting"] <= cat["distributors"]

    row = next(p for p in generated["proof"] if "catalogue" in p["label"].lower())
    if db["partsPriced"] != db["parts"]:
        assert str(db["partsPriced"]) in row["detail"] and str(db["parts"]) in row["detail"], (
            "when coverage is partial the page must state BOTH the priced count and the total"
        )
    if db["distributorsQuoting"] != db["distributors"]:
        assert str(db["distributorsQuoting"]) in row["detail"], (
            "the page must state how many distributors actually quote, not just how many exist"
        )


def test_the_offers_are_never_described_as_live(generated):
    """`distributor_offers` has no date column, so freshness is unfalsifiable from the data.

    The vintage is a static 2024 snapshot asserted in backend/seeds/seed_db.py and
    docs/DATA_PROVENANCE.md. Calling it "live" claims something the schema cannot support —
    and the standing bar is that nothing published may be contradicted by the code.
    """
    con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    try:
        cols = {r[1].lower() for r in con.execute("PRAGMA table_info(distributor_offers)")}
    finally:
        con.close()
    dated = cols & {"updated_at", "observed_at", "fetched_at", "as_of", "created_at", "date"}
    assert not dated, (
        f"distributor_offers now has {dated} — if offers really are dated, revisit this test "
        "and the wording it guards rather than deleting it"
    )

    blob = " ".join(
        [p["detail"] + " " + p["label"] + " " + p["value"] for p in generated["proof"]]
        + [s["detail"] + " " + s["label"] for s in generated["stats"].values()]
    ).lower()
    assert "live offer" not in blob, "offers described as live, but nothing in the data dates them"

    row = next(p for p in generated["proof"] if "catalogue" in p["label"].lower())
    assert "snapshot" in row["detail"].lower(), "the static vintage must be stated, not implied"


def test_the_generator_is_deterministic_and_the_committed_file_is_current():
    """Regenerating must reproduce the committed file byte for byte.

    Two failures in one assertion:

    * NONDETERMINISM. The generator briefly wrote a `Generated: <now>` line, so every
      `npm run build` dirtied the tree for a diff carrying no information. That is not
      cosmetic in this repo — artifacts stamp `provenance.git.dirty`, and one
      regenerated after a build would have recorded itself irreproducible because of a
      comment.
    * STALENESS. If an artifact moves and nobody reruns the generator, the committed
      module still holds the old numbers. The other tests here compare the COMMITTED
      module against the artifacts, so they catch that too — but this one names it
      precisely, and points at the command that fixes it.
    """
    script = REPO / "frontend" / "scripts" / "build-landing-data.mjs"
    if not shutil.which("node"):
        pytest.skip("node not available")

    before = GENERATED.read_text()
    proc = subprocess.run(
        ["node", str(script)], cwd=REPO / "frontend",
        capture_output=True, text=True, timeout=120,
    )
    assert proc.returncode == 0, f"generator failed: {proc.stderr[-500:]}"
    after = GENERATED.read_text()

    if before != after:
        GENERATED.write_text(before)  # leave the tree as we found it
        pytest.fail(
            "regenerating landingData.ts changed it. Either the generator is not "
            "deterministic, or an artifact moved and the committed file was never "
            "refreshed. Run: cd frontend && node scripts/build-landing-data.mjs"
        )


def test_every_published_number_names_its_source(generated):
    """The differentiator of this project is traceability — enforce it structurally."""
    for stat in generated["stats"].values():
        assert stat["source"].strip(), f"{stat['id']} has no source"
        assert "→" in stat["source"] or stat["source"].startswith("backend/"), (
            f"{stat['id']} source is not a path into an artifact: {stat['source']!r}"
        )
    for row in generated["proof"]:
        assert row["source"].strip(), f"proof point {row['label']!r} has no source"
