"""
Solomon (1987) CVRPTW benchmark instances and their published reference values.

THE INSTANCES. 56 instances in six families: C1 (C101-C109), C2 (C201-C208),
R1 (R101-R112), R2 (R201-R211), RC1 (RC101-RC108), RC2 (RC201-RC208).
C = clustered customers, R = random, RC = mixed; family 1 has short time
windows and small vehicles, family 2 long windows and large vehicles. Each
instance has 100 customers; the standard 25- and 50-customer versions are the
first 25 / 50 customers of the 100-customer file with the same depot, fleet
and horizon.

Files live in ``app/vrp/data/solomon/`` as ``c101.txt`` (100 customers),
``c101_25.txt`` and ``c101_50.txt``. They are regenerated byte-for-byte by
``backend/scripts/download_solomon_instances.py`` from the SINTEF TOP backup
of Solomon's instance definitions:

    https://www.sintef.no/globalassets/project/top/vrptw/solomon/solomon-100.zip
    sha256 8a0a72cbe6b7f8f9988ace4ebde0378ec34943acaaac47f2c408915e41887747

Source: M. M. Solomon, "Algorithms for the Vehicle Routing and Scheduling
Problems with Time Window Constraints", Operations Research 35(2), 1987,
254-265; instance page http://web.cba.neu.edu/~msolomon/problems.htm. The
instances carry no explicit license; they are published by their author for
research benchmarking and are redistributed here, unchanged, on that basis
with this citation.

REFERENCE VALUES. ``data/solomon/best_known.json`` holds, per instance and
size, the published reference value and its source (see that file's
``sources`` and ``references``):

* 100 customers - SINTEF TOP best known solutions (hierarchical objective:
  fewest vehicles first, then distance; double precision; two decimals).
* 25 / 50 customers - Solomon's table of proven optima (objective: distance
  only; the exact-method convention truncates each arc to one decimal).
  ``None`` where that table lists no optimum.

INTEGER SCALING. The shared model (``app.vrp.model``) is integer-only. Loaded
instances multiply every distance and time by :data:`SCALE` (100):

* ``distance`` - Euclidean distance x 100, rounded to nearest (the objective);
* ``travel_time`` - Euclidean distance x 100, rounded UP, and time windows and
  service times x 100 exactly. Rounding travel up makes every schedule the
  integer validator accepts feasible in real arithmetic too, so a "feasible"
  benchmark result is feasible under the published double-precision rules.

Reported distances never come from the scaled integers: :func:`route_distance`
recomputes them from the coordinates in double precision (or with the
one-decimal truncation, for comparison with the 25/50-customer optima).
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from functools import lru_cache
from itertools import pairwise
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

from app.vrp.model import Node, VrpInstance

DATA_DIR = Path(__file__).parent / "data" / "solomon"

#: Integer scale applied to distances and times when building a :class:`VrpInstance`.
SCALE = 100

#: Customer counts of the standard instance versions.
SIZES = (25, 50, 100)

FAMILIES: Dict[str, List[str]] = {
    "C1": [f"C1{i:02d}" for i in range(1, 10)],
    "C2": [f"C2{i:02d}" for i in range(1, 9)],
    "R1": [f"R1{i:02d}" for i in range(1, 13)],
    "R2": [f"R2{i:02d}" for i in range(1, 12)],
    "RC1": [f"RC1{i:02d}" for i in range(1, 9)],
    "RC2": [f"RC2{i:02d}" for i in range(1, 9)],
}

#: All 56 instance names, in family order.
INSTANCE_NAMES: List[str] = [name for names in FAMILIES.values() for name in names]


@dataclass(frozen=True)
class SolomonInstance:
    """One Solomon instance exactly as the file states it (real units, depot first)."""

    name: str
    num_customers: int
    num_vehicles: int
    vehicle_capacity: int
    coords: List[Tuple[float, float]]
    demand: List[int]
    ready: List[int]
    due: List[int]
    service_time: List[int]

    @property
    def family(self) -> str:
        return family_of(self.name)

    def to_vrp(self) -> VrpInstance:
        """The instance in the shared integer model, scaled by :data:`SCALE`."""
        dists = [[math.dist(a, b) for b in self.coords] for a in self.coords]
        nodes = [
            Node(
                demand=0 if i == 0 else self.demand[i],
                ready=self.ready[i] * SCALE,
                due=self.due[i] * SCALE,
                service_time=0 if i == 0 else self.service_time[i] * SCALE,
            )
            for i in range(len(self.coords))
        ]
        return VrpInstance(
            nodes=nodes,
            distance=[[int(round(d * SCALE)) for d in row] for row in dists],
            travel_time=[[_ceil_scaled(d) for d in row] for row in dists],
            num_vehicles=self.num_vehicles,
            vehicle_capacity=self.vehicle_capacity,
            name=f"solomon_{self.name}_{self.num_customers}",
        )


def _ceil_scaled(d: float) -> int:
    # The tiny epsilon keeps exact integer distances (e.g. 5.0 -> 500) from rounding up on float noise.
    return int(math.ceil(d * SCALE - 1e-9))


def family_of(name: str) -> str:
    """``"RC104"`` -> ``"RC1"``."""
    name = name.upper()
    return name[:-2]


def instance_path(name: str, num_customers: int) -> Path:
    """Path of the file for ``name`` (e.g. ``"C101"``) at ``num_customers`` (25, 50 or 100)."""
    if name.upper() not in INSTANCE_NAMES:
        raise ValueError(f"unknown Solomon instance {name!r}")
    if num_customers not in SIZES:
        raise ValueError(f"num_customers must be one of {SIZES}, got {num_customers}")
    suffix = "" if num_customers == 100 else f"_{num_customers}"
    return DATA_DIR / f"{name.lower()}{suffix}.txt"


def parse_solomon_file(path: Path) -> SolomonInstance:
    """Parse a Solomon instance file in the standard layout.

    The layout is: the instance name; a ``VEHICLE`` block whose ``NUMBER
    CAPACITY`` header is followed by the two values; a ``CUSTOMER`` block whose
    ``CUST NO.`` header is followed by one row per node (``id x y demand ready
    due service``), depot first with id 0.
    """
    lines = path.read_text().splitlines()
    name = lines[0].strip().upper()
    num_vehicles = vehicle_capacity = None
    rows: List[List[str]] = []
    in_customers = False
    for i, line in enumerate(lines):
        upper = line.upper()
        if "NUMBER" in upper and "CAPACITY" in upper:
            num_vehicles, vehicle_capacity = (int(v) for v in lines[i + 1].split()[:2])
        elif upper.strip().startswith("CUST NO."):
            in_customers = True
        elif in_customers and line.split():
            fields = line.split()
            if len(fields) != 7:
                raise ValueError(f"{path}: expected 7 fields per customer row, got {line!r}")
            rows.append(fields)
    if num_vehicles is None or vehicle_capacity is None:
        raise ValueError(f"{path}: no NUMBER / CAPACITY block")
    if not rows or int(rows[0][0]) != 0:
        raise ValueError(f"{path}: the first customer row must be the depot (id 0)")
    for k, fields in enumerate(rows):
        if int(fields[0]) != k:
            raise ValueError(f"{path}: customer ids must run 0..n in order, found {fields[0]} at row {k}")
    return SolomonInstance(
        name=name,
        num_customers=len(rows) - 1,
        num_vehicles=num_vehicles,
        vehicle_capacity=vehicle_capacity,
        coords=[(float(r[1]), float(r[2])) for r in rows],
        demand=[int(r[3]) for r in rows],
        ready=[int(r[4]) for r in rows],
        due=[int(r[5]) for r in rows],
        service_time=[int(r[6]) for r in rows],
    )


def read_solomon(name: str, num_customers: int) -> SolomonInstance:
    """The raw instance ``name`` at ``num_customers`` customers."""
    inst = parse_solomon_file(instance_path(name, num_customers))
    if inst.num_customers != num_customers:
        raise ValueError(f"{name}/{num_customers}: file has {inst.num_customers} customers")
    return inst


def load_solomon(name: str, num_customers: int) -> VrpInstance:
    """Instance ``name`` (e.g. ``"C101"``) with ``num_customers`` customers, in the shared model."""
    return read_solomon(name, num_customers).to_vrp()


def route_distance(
    coords: Sequence[Tuple[float, float]], routes: Sequence[Sequence[int]], truncate_one_decimal: bool = False
) -> float:
    """Total Euclidean length of ``routes`` (depot legs included), in real units.

    With ``truncate_one_decimal`` every arc is truncated to one decimal first,
    the convention of the published 25/50-customer optima.
    """
    total = 0.0
    for route in routes:
        path = [0, *route, 0]
        for a, b in pairwise(path):
            d = math.dist(coords[a], coords[b])
            total += math.floor(d * 10 + 1e-9) / 10 if truncate_one_decimal else d
    return total


@lru_cache(maxsize=1)
def _best_known_file() -> dict:
    return json.loads((DATA_DIR / "best_known.json").read_text())


def best_known_sources() -> dict:
    """The ``sources`` and ``references`` sections of ``best_known.json``."""
    data = _best_known_file()
    return {"sources": data["sources"], "references": data["references"]}


def get_best_known(name: str, num_customers: int) -> Optional[dict]:
    """Published reference for ``name`` at ``num_customers``, or ``None`` if none is published.

    The dict has ``vehicles``, ``distance`` (as published), ``reference``
    (author key) and ``source`` (``"sintef_best_known"`` or ``"solomon_optimal"``).
    """
    instance_path(name, num_customers)  # validates both arguments
    entry = _best_known_file()["instances"][name.upper()][str(num_customers)]
    return dict(entry) if entry is not None else None
